# Generated by Django 2.2.4 on 2019-08-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=128)),
                ('telefone', models.CharField(max_length=32)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=128)),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
