# Generated by Django 2.2.4 on 2019-08-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('tempo_notificacao', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='config_id',
            field=models.ManyToManyField(to='users.UserConfig'),
        ),
    ]
