# Generated by Django 2.2.4 on 2019-09-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190925_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=128),
        ),
    ]
