# Generated by Django 2.2.4 on 2019-09-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190925_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='config_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tempo_notificacao',
            field=models.IntegerField(default=30),
        ),
        migrations.DeleteModel(
            name='UserConfig',
        ),
    ]
