# Generated by Django 2.2.6 on 2019-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190929_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tempo_notificacao',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
