# Generated by Django 2.2.4 on 2019-11-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191010_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tempo_notificacao',
        ),
    ]
