# Generated by Django 2.2.4 on 2019-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
