# Generated by Django 2.2.4 on 2019-09-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_scrapyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
