# Generated by Django 2.2.4 on 2019-09-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_atual',
            field=models.TextField(null=True),
        ),
    ]
