# Generated by Django 2.2.4 on 2019-10-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20190925_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
        migrations.RemoveField(
            model_name='fornecedorproduto',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ManyToManyField(to='produtos.FornecedorProduto'),
        ),
    ]
