# Generated by Django 2.2.6 on 2019-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20191001_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome_fornecedor',
            field=models.ManyToManyField(null=True, to='produtos.FornecedorProduto'),
        ),
    ]
