# Generated by Django 2.2.4 on 2019-11-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20191017_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome_fornecedor',
        ),
        migrations.DeleteModel(
            name='FornecedorProduto',
        ),
    ]
