# Generated by Django 2.2.4 on 2019-11-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_auto_20191113_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tempo_notificacao',
            field=models.IntegerField(blank=True, default=30),
        ),
    ]
