# Generated by Django 2.2.4 on 2019-11-22 17:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0012_auto_20191115_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicopreco',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('vista', models.BooleanField(default=0)),
                ('data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mensagem', models.TextField()),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
